= Asciidoctor Theory of Operation: Enough Stuff to Write an Extension
Tom Nurkkala <tnurkkala@cse.taylor.edu>
V0.1, January, 2016

== Introduction

These are the key classes in Asciidoctor
that you should understand in order
to build extensions.


[plantuml, diagram-classes, png]
.Class Diagram for key Asciidoctor classes
....
hide empty members

abstract class AbstractNode {
    attributes: Hash
    context: Symbol
    document: Asciidoctor::Document
    id: String
    node_name: String
    parent

    initialize(parent, context, opts)
    converter()
    role()
}

AbstractNode <|-- AbstractBlock

abstract class AbstractBlock {
    blocks: Array
    content_model: Symbol
    style: String
    subs: Array

    initialize(parent, context, opts)
    content()
    convert()
    find_by(selector, &block)
}

AbstractBlock <|-- Document
Document *-- Footnote
Document *--AttributeEntry
Document *--Title

class Document {
    converter: Converter
    extensions: Array
    parsed: Boolean
    reader: Reader

    initialize(data, options)
    content()
    convert(opts)
    parse(data)
    write(output, target)
}

AbstractBlock <|-- Block

class Block {
    lines

    initialize(parent, context, opts)
    content()
    source()
}

AbstractBlock <|-- Section

class Section {
    index
    level
    numbered

    initialize(parent, level, numbered, opts)
    generate_id()
    sectnum()
}

AbstractBlock <|-- Table
AbstractBlock <|-- ListItem
AbstractBlock <|-- List

class Reader {
'    initialize(data, cursor, opts)
}

Reader <|-- PreprocessorReader

class PreprocessorReader {
'    initialize(document, data, cursor)
}

class Parser {
    parse(reader, document, options)
    parse_document_header(reader, document)
    next_section(reader, parent, attributes)
    next_block(reader, parent, attributes, options)
}
note right of Parser : Can't be instantiated
....

[plantuml, diagram-processors, png]
.Class Diagram for Processors
....
hide empty members

Processor <|-- Preprocessor
Processor <|-- Treprocessor
Processor <|-- Postprocessor
Processor <|-- IncludeProcessor
Processor <|-- DocinfoProcessor
Processor <|-- BlockProcessor
Processor <|-- MacroProcessor
MacroProcessor <|-- BlockMacroProcessor
MacroProcessor <|-- InlineMacroProcessor

class Registry {
    document
    initialize(groups)
    -- Document processors --
    preprocessor(args, &block)
    preprocessors?()
    preprocessors()
    ..
    Similar for TreeProcessor,
    PostProcessor, IncludeProcessor,
    DocInfoProcessor
    -- Syntax processors --
    block(args, block)
    blocks?()
    registered_for_block?(name, context)
    find_block_extension(name)
    ..
    Similar for BlockMacroProcessor,
    InlineMacroProcessor
    -- Private Methods --
    add_document_processor(kind, args, &block)
    add_syntax_processor(kind, args, &block)
}
....

[plantuml, diagram-converters, png]
.Class Diagram for Converters
....
hide empty members
class Base
class BuiltIn {
    initialize(backend, opts)
    convert(node, transform, opts)
    content(node)
}
Base <|-- CompositeConverter
BuiltIn <|-- Html5Converter
BuiltIn <|-- DocBook5Converter
BuiltIn <|-- ManPageConverter
Base <|-- TemplateConverter
....

[plantuml, diagram-modules, png]
.Key Asciidoctor Modules
....
class Cli << (M, salmon) >> {
    documents

    initialize(*options)
    invoke!()
}

class Asciidoctor << (M, salmon) >> {
    Many constants
    Many regular expressions
    --
    load(input, options)
    load_file(filename, options)
    convert(input, options)
    convert_file(filename, options)
}

....


[plantuml, diagram-sequence, png]
....
participant Cli << (M, salmon) >>
participant AD as "Asciidoctor" << (M, salmon) >>
participant Document
participant Reader as "PreprocessorReader"
participant Parser
participant Converter << (M, salmon) >>
participant Ext as "Extension"

Cli -> AD : convert(input, options)
activate AD

    AD -> AD : load(input, options)
    activate AD

        create Document
        AD -> Document : (new)

        AD -> Document : initialize(lines, options)
        activate Document

            create Reader
            Document -> Reader : (new)

            Document -> Reader : initialize(data)
            activate Reader

            Document <-- Reader: reader
            deactivate Reader

        AD <-- Document : document
        deactivate Document

        AD -> Document : parse()
        activate Document

            Document -> Ext : process_method()
            note right : Preprocessor
            activate Ext
            Document <-- Ext : reader
            deactivate Ext

            Document -> Parser : parse(reader, document)
            activate Parser

                Parser -> Parser : parse_document_header(reader, document)

                Parser -> Parser : next_section(reader, document)
                activate Parser

                    Parser -> Parser: next_block(reader, parent, attributes, options)
                    note left : Main entry point
                    activate Parser

                        Parser -> Ext : process_method()
                        note right : BlockMacroProcessor
                        activate Ext
                        Parser <-- Ext : block
                        deactivate Ext

                        Parser -> Parser : build_block(...)
                        activate Parser

                            Parser -> Ext : process_method()
                            note right : BlockProcessor
                            activate Ext
                            Parser <-- Ext : block
                            deactivate Ext

                        Parser <-- Parser : block
                        deactivate Parser

                    Parser <-- Parser : block
                    deactivate Parser

                deactivate Parser

            Document <-- Parser  : document
            deactivate Parser

            Document -> Ext : process_method()
            note right : Treeprocessor
            activate Ext
            Document <-- Ext : result
            deactivate Ext

        AD <-- Document : document
        deactivate Document

    deactivate AD

    AD -> Document : convert(options)
    activate Document

        Document -> Converter : convert()
        activate Converter
        Document <-- Converter : output
        deactivate Converter

        Document -> Ext : process_method()
        note right : Postprocessor
        activate Ext
        Document <-- Ext : result
        deactivate Ext

    AD <-- Document : output
    deactivate Document

    AD -> Document : write(output, outputfile)
    activate Document

        Document -> Converter: write(output, target)
        activate Converter
        deactivate Converter

    deactivate Document

Cli <-- AD : document
deactivate AD
....

=== Abstract Node

The `converter()` method is a simple proxy to the converter
defined on the document object that contains this node.

The abstract node contains attributes for the node.
A role is stored as an attribute under `attributes['role']`.

Values for `context`

. `:document`
. `:section`

=== Abstract Block

The `convert()` method invokes the `convert()` method
of the converter retrieved from the abstract node.

The `content()` method invokes `convert()`
on all of the children blocks
and concatenates them into a single string
(joined with the end-of-line characters).

The `find_by()` method traverse all descendant blocks
searching for those that match by one or more of:

. context (Symbol)
. style (String)
. role (String)

If there's a block provided,
it's used as an additional filter.


==== Instance Variables

`@blocks`:: children of this block

`@content_model`:: Type of content that a block can contain;
    takes one of the following values:
    . `:compound` (default) -- block can contain other blocks
    . `:empty` -- block is empty (audio, image, page break)
    . `:raw` -- block contains unprocessed content (pass)
    . `:simple` --
    . `:verbatim` -- verbatim content (listing, literal)

`@id`:: Block's identifier, also known as an _anchor_, set by `[[\...]]`

`@style`:: Style of the block (??)

`@subs`:: Substitutions applied to the block's content

==== Methods

```
initialize(parent, content, opts)
```

`parent`:: Block's parent

`context`:: ?? One of:
    . `:document`
    . `:section`

`convert`:: Convert the string content for the block.
    Also converts the children of the block.
    Invokes `Converter::convert`

=== Document

* `input_opts` includes `:to_file` destination.
